/**
 * Deterministic GitHub workflow templates for known toolchains.
 *
 * The LLM build-process configurator owns workflow generation per project
 * (any ecosystem). These templates serve two roles: (1) few-shot reference
 * embedded in the evidence bundle for node projects, (2) fallback the
 * server applies when the LLM's resolution left CI uncovered. Commands come
 * straight from the project's BuildToolchain spec so CI runs the exact same
 * surface SlopControl runs locally.
 */

import type { BuildToolchainSpec } from "@slopcontrol/types";
import {
  toolchainBuildCmd,
  toolchainBumpVersionCmd,
  toolchainInstallCmd,
  toolchainPublishCmd,
} from "./build-toolchain.js";
import { NPM_PRIVATE_SCOPES } from "./npm-registry.js";

function shellLine(cmd: string[]): string {
  return cmd.join(" ");
}

/**
 * Golden .npmrc for node projects consuming SlopControl private scopes.
 * pnpm does NOT expand ${VAR} in committed project-level registry/auth lines,
 * so the committed file uses the literal loopback registry (not a secret);
 * containers/CI generate their own .npmrc at build time (see golden Dockerfile).
 */
export function goldenProjectNpmrc(scopes: readonly string[]): string {
  const lines = scopes.map(
    (scope) => `${scope}:registry=http://127.0.0.1:4873/`,
  );
  return [
    "# SlopControl local registry — literal loopback (pnpm ignores \\${VAR}-style",
    "# env references in committed project .npmrc registry/auth lines). Docker",
    "# builds and CI generate their own .npmrc from build ARGs / secrets.",
    ...lines,
    "",
  ].join("\n");
}

/**
 * Golden Dockerfile dependency stage for node-pnpm consumers of the private
 * registry: registry coordinates arrive as build ARGs (never hard-coded),
 * the container .npmrc is generated from them, install is lockfile-frozen.
 */
export function goldenDockerfileDepsSection(scopes: readonly string[]): string {
  const printfScopes = scopes.map((s) => `${s}:registry=%s\\n`).join("");
  const printfArgs = scopes
    .map(() => '"$SLOPCONTROL_NPM_REGISTRY_DOCKER_URL"')
    .join(" ");
  return [
    "# --- SlopControl registry contract (golden) ---",
    "ARG SLOPCONTROL_NPM_REGISTRY_DOCKER_URL",
    "ARG SLOPCONTROL_NPM_REGISTRY_DOCKER_AUTH_HOST",
    "ARG SLOPCONTROL_NPM_REGISTRY_TOKEN",
    "# pnpm does not expand env vars in a committed project .npmrc — generate",
    "# the container .npmrc from the build ARGs instead.",
    `RUN printf '${printfScopes}//%s/:_authToken=%s\\n' ${printfArgs} "$SLOPCONTROL_NPM_REGISTRY_DOCKER_AUTH_HOST" "$SLOPCONTROL_NPM_REGISTRY_TOKEN" > .npmrc`,
    "RUN pnpm install --frozen-lockfile",
  ].join("\n");
}

/** Placeholder → env ref so workflows never hard-code registry coordinates. */
function ciSubstitute(cmd: string[]): string[] {
  return cmd.map((arg) =>
    arg
      .replace(/\{registryUrl\}/g, '"$SLOPCONTROL_NPM_REGISTRY_URL"')
      .replace(/\{bump\}/g, "patch")
      .replace(/\{dep\}/g, '"$PACKAGE_DEP"'),
  );
}

function setupStepsYaml(spec: BuildToolchainSpec): string[] {
  if (spec.kind === "node-pnpm") {
    return [
      "      - uses: actions/checkout@v4",
      "      - uses: pnpm/action-setup@v4",
      "        with:",
      "          version: 9",
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 22",
      "          cache: pnpm",
    ];
  }
  if (spec.kind === "node-npm") {
    return [
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 22",
      "          cache: npm",
    ];
  }
  return [];
}

/** ci.yml: install (frozen) → build. Null for ecosystems without defaults. */
export function renderCiWorkflowYaml(
  spec: BuildToolchainSpec,
  scopes: readonly string[] = NPM_PRIVATE_SCOPES,
): string | null {
  const setup = setupStepsYaml(spec);
  const install = toolchainInstallCmd(spec, { frozen: true });
  const build = toolchainBuildCmd(spec);
  if (!setup.length || !install || !build) return null;
  // Registry-aware toolchains must resolve private scopes on CI too — pnpm
  // does not expand env vars in a committed project .npmrc, so generate it.
  const npmrcStep = spec.registryEnvKeys.length
    ? [
        "      - name: Generate .npmrc from SlopControl secrets",
        "        env:",
        "          SLOPCONTROL_NPM_REGISTRY_URL: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_URL }}",
        "          SLOPCONTROL_NPM_REGISTRY_AUTH_HOST: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_AUTH_HOST }}",
        "          SLOPCONTROL_NPM_REGISTRY_TOKEN: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_TOKEN }}",
        "        run: |",
        `          printf '${scopes.map((s) => `${s}:registry=%s\\n`).join("")}//%s/:_authToken=%s\\n' ${scopes.map(() => '"$SLOPCONTROL_NPM_REGISTRY_URL"').join(" ")} "$SLOPCONTROL_NPM_REGISTRY_AUTH_HOST" "$SLOPCONTROL_NPM_REGISTRY_TOKEN" > .npmrc`,
      ]
    : [];
  return [
    "# Generated by SlopControl — CI runs the same toolchain commands as local dev.",
    "name: ci",
    "on:",
    "  push:",
    "  pull_request:",
    "jobs:",
    "  build:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    ...setup,
    ...npmrcStep,
    "      - name: Install",
    `        run: ${shellLine(install)}`,
    "      - name: Build",
    `        run: ${shellLine(build)}`,
    "",
  ].join("\n");
}

/**
 * publish.yml for component libraries: install → build → bump → publish,
 * registry URL/token from GitHub secrets (never literals).
 */
export function renderPublishWorkflowYaml(
  spec: BuildToolchainSpec,
): string | null {
  const setup = setupStepsYaml(spec);
  const install = toolchainInstallCmd(spec, { frozen: true });
  const build = toolchainBuildCmd(spec);
  const bump = toolchainBumpVersionCmd(spec, "patch");
  const publish = toolchainPublishCmd(spec, "{registryUrl}");
  if (!setup.length || !install || !build || !bump || !publish) return null;
  return [
    "# Generated by SlopControl — publish via the project's own toolchain.",
    "# Registry coordinates come from GitHub secrets, matching local .env.docker.",
    "name: publish",
    "on:",
    "  workflow_dispatch:",
    "  push:",
    "    tags:",
    '      - "v*"',
    "jobs:",
    "  publish:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    ...setup,
    "      - name: Install",
    `        run: ${shellLine(install)}`,
    "      - name: Build",
    `        run: ${shellLine(build)}`,
    "      - name: Bump version",
    `        run: ${shellLine(bump)}`,
    "      - name: Configure registry auth",
    "        # pnpm/npm do not expand env vars in committed project .npmrc",
    "        # registry/auth lines — generate the auth line at runtime.",
    "        run: |",
    '          if [ -n "$SLOPCONTROL_NPM_REGISTRY_TOKEN" ]; then',
    '            printf \'//%s/:_authToken=%s\\n\' "$SLOPCONTROL_NPM_REGISTRY_AUTH_HOST" "$SLOPCONTROL_NPM_REGISTRY_TOKEN" >> .npmrc',
    "          fi",
    "        env:",
    "          SLOPCONTROL_NPM_REGISTRY_AUTH_HOST: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_AUTH_HOST }}",
    "          SLOPCONTROL_NPM_REGISTRY_TOKEN: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_TOKEN }}",
    "      - name: Publish",
    `        run: ${shellLine(ciSubstitute(publish))}`,
    "        env:",
    "          SLOPCONTROL_NPM_REGISTRY_URL: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_URL }}",
    "          SLOPCONTROL_NPM_REGISTRY_TOKEN: ${{ secrets.SLOPCONTROL_NPM_REGISTRY_TOKEN }}",
    "",
  ].join("\n");
}
