/**
 * SlopControl private npm registry — paths, config, .npmrc, storage listing.
 * Process lifecycle (Verdaccio spawn) lives in apps/server.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { z } from "zod";

export const DEFAULT_NPM_REGISTRY_PORT = 4873;
export const NPM_PRIVATE_SCOPES = ["@jam", "@slopcontrol"] as const;

export const NpmRegistryMetaSchema = z.object({
  url: z.string(),
  host: z.string().default("127.0.0.1"),
  port: z.number().int().positive(),
  status: z.enum(["stopped", "starting", "up", "error"]).default("stopped"),
  pid: z.number().int().positive().optional(),
  scopes: z.array(z.string()).default([...NPM_PRIVATE_SCOPES]),
  authToken: z.string().min(8),
  createdAt: z.string(),
  updatedAt: z.string(),
  lastError: z.string().optional(),
});
export type NpmRegistryMeta = z.infer<typeof NpmRegistryMetaSchema>;

export function npmRegistryRoot(dataDir: string): string {
  return join(dataDir, "npm-registry");
}

export function npmRegistryStorageDir(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "storage");
}

export function npmRegistryConfigPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "config.yaml");
}

export function npmRegistryMetaPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "REGISTRY.json");
}

export function npmRegistryHtpasswdPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "htpasswd");
}

export function resolveNpmRegistryPort(): number {
  const raw = process.env.SLOPCONTROL_NPM_REGISTRY_PORT;
  const n = raw ? Number(raw) : DEFAULT_NPM_REGISTRY_PORT;
  return Number.isFinite(n) && n > 0 ? Math.floor(n) : DEFAULT_NPM_REGISTRY_PORT;
}

export function isNpmRegistryDisabled(): boolean {
  const v = (process.env.SLOPCONTROL_NPM_REGISTRY ?? "1").trim().toLowerCase();
  return v === "0" || v === "false" || v === "off" || v === "no";
}

export function readNpmRegistryMeta(dataDir: string): NpmRegistryMeta | null {
  const path = npmRegistryMetaPath(dataDir);
  if (!existsSync(path)) return null;
  try {
    return NpmRegistryMetaSchema.parse(JSON.parse(readFileSync(path, "utf-8")));
  } catch {
    return null;
  }
}

export function writeNpmRegistryMeta(
  dataDir: string,
  meta: NpmRegistryMeta,
): void {
  mkdirSync(npmRegistryRoot(dataDir), { recursive: true });
  writeFileSync(
    npmRegistryMetaPath(dataDir),
    `${JSON.stringify(meta, null, 2)}\n`,
    "utf-8",
  );
}

/** Verdaccio YAML config — private scopes local-only; everything else proxies npmjs. */
export function buildVerdaccioConfigYaml(opts: {
  storageDir: string;
  htpasswdPath: string;
  host: string;
  port: number;
}): string {
  // Paths as absolute — Verdaccio resolves relative to config file dir otherwise.
  const storage = opts.storageDir.replace(/\\/g, "/");
  const htpasswd = opts.htpasswdPath.replace(/\\/g, "/");
  return `# Generated by SlopControl — private npm registry (Verdaccio)
storage: ${JSON.stringify(storage)}
plugins: ./plugins
web:
  enable: true
  title: SlopControl npm
auth:
  htpasswd:
    file: ${JSON.stringify(htpasswd)}
    max_users: 10
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 30s
packages:
  '@jam/*':
    access: $all
    publish: $all
    unpublish: $all
  '@slopcontrol/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
log: { type: stdout, format: pretty, level: warn }
listen: ${opts.host}:${opts.port}
`;
}

/**
 * Ensure registry disk layout + REGISTRY.json + config.yaml.
 * Does not start Verdaccio.
 */
export function ensureNpmRegistryLayout(dataDir: string): NpmRegistryMeta {
  const root = npmRegistryRoot(dataDir);
  const storage = npmRegistryStorageDir(dataDir);
  const htpasswd = npmRegistryHtpasswdPath(dataDir);
  mkdirSync(storage, { recursive: true });
  mkdirSync(join(root, "plugins"), { recursive: true });

  const port = resolveNpmRegistryPort();
  const host = "127.0.0.1";
  const url = `http://${host}:${port}/`;
  const now = new Date().toISOString();
  const prior = readNpmRegistryMeta(dataDir);
  const authToken = prior?.authToken ?? randomBytes(24).toString("hex");

  const meta = NpmRegistryMetaSchema.parse({
    url,
    host,
    port,
    status: prior?.status === "up" ? "up" : "stopped",
    pid: prior?.pid,
    scopes: [...NPM_PRIVATE_SCOPES],
    authToken,
    createdAt: prior?.createdAt ?? now,
    updatedAt: now,
    lastError: prior?.lastError,
  });

  writeFileSync(
    npmRegistryConfigPath(dataDir),
    buildVerdaccioConfigYaml({
      storageDir: storage,
      htpasswdPath: htpasswd,
      host,
      port,
    }),
    "utf-8",
  );
  if (!existsSync(htpasswd)) {
    writeFileSync(htpasswd, "", "utf-8");
  }
  writeNpmRegistryMeta(dataDir, meta);
  return meta;
}

export function formatScopedNpmrc(opts: {
  registryUrl: string;
  authToken: string;
  scopes?: string[];
}): string {
  const url = opts.registryUrl.endsWith("/")
    ? opts.registryUrl
    : `${opts.registryUrl}/`;
  const hostPort = url.replace(/^https?:\/\//, "").replace(/\/$/, "");
  const scopes = opts.scopes?.length
    ? opts.scopes
    : [...NPM_PRIVATE_SCOPES];
  const lines: string[] = [
    "# SlopControl private npm registry — scoped packages only",
    `# Registry: ${url}`,
  ];
  for (const scope of scopes) {
    const s = scope.startsWith("@") ? scope : `@${scope}`;
    lines.push(`${s}:registry=${url}`);
  }
  lines.push(`//${hostPort}/:_authToken=${opts.authToken}`);
  lines.push("always-auth=true");
  return `${lines.join("\n")}\n`;
}

/**
 * Write/merge SlopControl scoped registry lines into a project's .npmrc.
 * Preserves unrelated lines; replaces prior SlopControl-managed block.
 */
export function ensureProjectNpmrc(opts: {
  projectRoot: string;
  registryUrl: string;
  authToken: string;
  scopes?: string[];
}): { path: string; written: boolean } {
  const path = join(opts.projectRoot, ".npmrc");
  const block = formatScopedNpmrc(opts);
  const markerStart = "# BEGIN slopcontrol-npm-registry";
  const markerEnd = "# END slopcontrol-npm-registry";
  const managed = `${markerStart}\n${block.trimEnd()}\n${markerEnd}\n`;

  let prior = "";
  if (existsSync(path)) {
    prior = readFileSync(path, "utf-8");
  }
  const re = new RegExp(
    `${markerStart.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${markerEnd.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`,
    "m",
  );
  let next: string;
  if (re.test(prior)) {
    next = prior.replace(re, managed);
  } else {
    next = prior.trimEnd()
      ? `${prior.trimEnd()}\n\n${managed}`
      : managed;
  }
  writeFileSync(path, next, "utf-8");
  return { path, written: true };
}

export type NpmRegistryPackageInfo = {
  name: string;
  versions: string[];
  latest?: string;
  path: string;
};

/** List packages from Verdaccio storage (local private packages). */
export function listNpmRegistryPackages(
  dataDir: string,
): NpmRegistryPackageInfo[] {
  const storage = npmRegistryStorageDir(dataDir);
  if (!existsSync(storage)) return [];
  const out: NpmRegistryPackageInfo[] = [];

  const visitPackageDir = (dir: string, name: string): void => {
    const metaPath = join(dir, "package.json");
    // Verdaccio stores as storage/@scope/name/package.json (couchdb doc)
    if (!existsSync(metaPath)) return;
    try {
      const doc = JSON.parse(readFileSync(metaPath, "utf-8")) as {
        name?: string;
        versions?: Record<string, unknown>;
        "dist-tags"?: { latest?: string };
      };
      const versions = Object.keys(doc.versions ?? {}).sort();
      if (!versions.length && !doc.name) return;
      out.push({
        name: doc.name ?? name,
        versions,
        latest: doc["dist-tags"]?.latest ?? versions[versions.length - 1],
        path: dir,
      });
    } catch {
      /* skip */
    }
  };

  for (const entry of readdirSync(storage)) {
    if (entry.startsWith(".")) continue;
    const full = join(storage, entry);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    if (entry.startsWith("@")) {
      for (const pkg of readdirSync(full)) {
        if (pkg.startsWith(".")) continue;
        visitPackageDir(join(full, pkg), `${entry}/${pkg}`);
      }
    } else {
      visitPackageDir(full, entry);
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

export function jamPackageNameForElement(elementId: string): string {
  const id = elementId
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "") || "element";
  return `@jam/${id}`;
}

/**
 * Scaffold an npm package directory from design-element src files.
 * Returns the package root path (created under elementVersionDir/npm-package).
 */
export function scaffoldElementNpmPackage(opts: {
  outDir: string;
  elementId: string;
  version: number | string;
  label?: string;
  srcFiles: Record<string, string>;
  description?: string;
}): {
  packageRoot: string;
  packageName: string;
  packageVersion: string;
  packageJsonPath: string;
} {
  const packageName = jamPackageNameForElement(opts.elementId);
  const packageVersion =
    typeof opts.version === "number"
      ? `${opts.version}.0.0`
      : String(opts.version);
  const packageRoot = opts.outDir;
  mkdirSync(packageRoot, { recursive: true });

  const files = { ...opts.srcFiles };
  if (!Object.keys(files).length) {
    files["index.js"] =
      `/** @jam/${opts.elementId} — placeholder */\nexport {};\n`;
  }

  // Prefer a single entry
  const entries = Object.keys(files);
  const mainFile =
    entries.find((f) => /^index\.(js|mjs|cjs|ts)$/i.test(f)) ||
    entries.find((f) => /\.(js|mjs|cjs)$/i.test(f)) ||
    entries[0]!;

  for (const [rel, body] of Object.entries(files)) {
    const dest = join(packageRoot, rel);
    mkdirSync(join(dest, ".."), { recursive: true });
    writeFileSync(dest, body, "utf-8");
  }

  // If only .ts sources, also write a thin .js re-export note via copying ts as main for consumers that use tsx/bundlers
  const pkg = {
    name: packageName,
    version: packageVersion,
    description:
      opts.description ||
      opts.label ||
      `SlopControl shared element ${opts.elementId}`,
    type: "module",
    main: mainFile,
    module: mainFile,
    types: mainFile.endsWith(".ts") ? mainFile : undefined,
    exports: {
      ".": {
        default: `./${mainFile}`,
        import: `./${mainFile}`,
      },
    },
    files: ["**/*"],
    keywords: ["slopcontrol", "jam", opts.elementId],
    license: "UNLICENSED",
    private: false,
    publishConfig: {
      access: "public",
    },
  };

  const packageJsonPath = join(packageRoot, "package.json");
  writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf-8");
  return { packageRoot, packageName, packageVersion, packageJsonPath };
}
