/**
 * SlopControl private npm registry — paths, config, .npmrc, storage listing.
 * Process lifecycle (Verdaccio spawn) lives in apps/server.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { z } from "zod";

export const DEFAULT_NPM_REGISTRY_PORT = 4873;
export const NPM_PRIVATE_SCOPES = ["@jam", "@jamroast", "@slopcontrol"] as const;

export const NpmRegistryMetaSchema = z.object({
  url: z.string(),
  host: z.string().default("127.0.0.1"),
  port: z.number().int().positive(),
  status: z.enum(["stopped", "starting", "up", "error"]).default("stopped"),
  pid: z.number().int().positive().optional(),
  scopes: z.array(z.string()).default([...NPM_PRIVATE_SCOPES]),
  authToken: z.string().min(8),
  createdAt: z.string(),
  updatedAt: z.string(),
  lastError: z.string().optional(),
  /** Evidence of library publishes (name → last published version). */
  publishedPackages: z
    .record(
      z.string(),
      z.object({
        version: z.string(),
        publishedAt: z.string(),
        toolchainKind: z.string().default(""),
      }),
    )
    .default({}),
});
export type NpmRegistryMeta = z.infer<typeof NpmRegistryMetaSchema>;

export function npmRegistryRoot(dataDir: string): string {
  return join(dataDir, "npm-registry");
}

export function npmRegistryStorageDir(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "storage");
}

export function npmRegistryConfigPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "config.yaml");
}

export function npmRegistryMetaPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "REGISTRY.json");
}

export function npmRegistryHtpasswdPath(dataDir: string): string {
  return join(npmRegistryRoot(dataDir), "htpasswd");
}

export function resolveNpmRegistryPort(): number {
  const raw = process.env.SLOPCONTROL_NPM_REGISTRY_PORT;
  const n = raw ? Number(raw) : DEFAULT_NPM_REGISTRY_PORT;
  return Number.isFinite(n) && n > 0 ? Math.floor(n) : DEFAULT_NPM_REGISTRY_PORT;
}

export function resolveNpmRegistryHost(): string {
  const raw = process.env.SLOPCONTROL_NPM_REGISTRY_HOST?.trim();
  return raw && raw.length > 0 ? raw : "127.0.0.1";
}

export function isNpmRegistryDisabled(): boolean {
  const v = (process.env.SLOPCONTROL_NPM_REGISTRY ?? "1").trim().toLowerCase();
  return v === "0" || v === "false" || v === "off" || v === "no";
}

export function readNpmRegistryMeta(dataDir: string): NpmRegistryMeta | null {
  const path = npmRegistryMetaPath(dataDir);
  if (!existsSync(path)) return null;
  try {
    return NpmRegistryMetaSchema.parse(JSON.parse(readFileSync(path, "utf-8")));
  } catch {
    return null;
  }
}

export function writeNpmRegistryMeta(
  dataDir: string,
  meta: NpmRegistryMeta,
): void {
  mkdirSync(npmRegistryRoot(dataDir), { recursive: true });
  writeFileSync(
    npmRegistryMetaPath(dataDir),
    `${JSON.stringify(meta, null, 2)}\n`,
    "utf-8",
  );
}

/** Verdaccio YAML config — private scopes local-only; everything else proxies npmjs. */
export function buildVerdaccioConfigYaml(opts: {
  storageDir: string;
  htpasswdPath: string;
  host: string;
  port: number;
}): string {
  // Paths as absolute — Verdaccio resolves relative to config file dir otherwise.
  const storage = opts.storageDir.replace(/\\/g, "/");
  const htpasswd = opts.htpasswdPath.replace(/\\/g, "/");
  return `# Generated by SlopControl — private npm registry (Verdaccio)
storage: ${JSON.stringify(storage)}
plugins: ./plugins
web:
  enable: true
  title: SlopControl npm
auth:
  htpasswd:
    file: ${JSON.stringify(htpasswd)}
    max_users: 10
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 30s
packages:
  '@jam/*':
    access: $all
    publish: $all
    unpublish: $all
  '@jamroast/*':
    access: $all
    publish: $all
    unpublish: $all
  '@slopcontrol/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
log: { type: stdout, format: pretty, level: warn }
listen: ${opts.host}:${opts.port}
`;
}

/**
 * Ensure registry disk layout + REGISTRY.json + config.yaml.
 * Does not start Verdaccio.
 */
export function ensureNpmRegistryLayout(dataDir: string): NpmRegistryMeta {
  const root = npmRegistryRoot(dataDir);
  const storage = npmRegistryStorageDir(dataDir);
  const htpasswd = npmRegistryHtpasswdPath(dataDir);
  mkdirSync(storage, { recursive: true });
  mkdirSync(join(root, "plugins"), { recursive: true });

  const port = resolveNpmRegistryPort();
  const host = resolveNpmRegistryHost();
  const url = `http://${host}:${port}/`;
  const now = new Date().toISOString();
  const prior = readNpmRegistryMeta(dataDir);
  const authToken = prior?.authToken ?? randomBytes(24).toString("hex");

  const meta = NpmRegistryMetaSchema.parse({
    url,
    host,
    port,
    status: prior?.status === "up" ? "up" : "stopped",
    pid: prior?.pid,
    scopes: [...NPM_PRIVATE_SCOPES],
    authToken,
    createdAt: prior?.createdAt ?? now,
    updatedAt: now,
    lastError: prior?.lastError,
  });

  writeFileSync(
    npmRegistryConfigPath(dataDir),
    buildVerdaccioConfigYaml({
      storageDir: storage,
      htpasswdPath: htpasswd,
      host,
      port,
    }),
    "utf-8",
  );
  if (!existsSync(htpasswd)) {
    writeFileSync(htpasswd, "", "utf-8");
  }
  writeNpmRegistryMeta(dataDir, meta);
  return meta;
}

export function formatScopedNpmrc(opts: {
  registryUrl: string;
  authToken: string;
  scopes?: string[];
}): string {
  const url = opts.registryUrl.endsWith("/")
    ? opts.registryUrl
    : `${opts.registryUrl}/`;
  const hostPort = url.replace(/^https?:\/\//, "").replace(/\/$/, "");
  const scopes = opts.scopes?.length
    ? opts.scopes
    : [...NPM_PRIVATE_SCOPES];
  const lines: string[] = [
    "# SlopControl private npm registry — scoped packages only",
    `# Registry: ${url}`,
  ];
  for (const scope of scopes) {
    const s = scope.startsWith("@") ? scope : `@${scope}`;
    lines.push(`${s}:registry=${url}`);
  }
  lines.push(`//${hostPort}/:_authToken=${opts.authToken}`);
  lines.push("always-auth=true");
  return `${lines.join("\n")}\n`;
}

/**
 * Write/merge SlopControl scoped registry lines into a project's .npmrc.
 * Preserves unrelated lines; replaces prior SlopControl-managed block.
 */
export function ensureProjectNpmrc(opts: {
  projectRoot: string;
  registryUrl: string;
  authToken: string;
  scopes?: string[];
}): { path: string; written: boolean } {
  const path = join(opts.projectRoot, ".npmrc");
  const block = formatScopedNpmrc(opts);
  const markerStart = "# BEGIN slopcontrol-npm-registry";
  const markerEnd = "# END slopcontrol-npm-registry";
  const managed = `${markerStart}\n${block.trimEnd()}\n${markerEnd}\n`;

  let prior = "";
  if (existsSync(path)) {
    prior = readFileSync(path, "utf-8");
  }
  const re = new RegExp(
    `${markerStart.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${markerEnd.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`,
    "m",
  );
  let next: string;
  if (re.test(prior)) {
    next = prior.replace(re, managed);
  } else {
    next = prior.trimEnd()
      ? `${prior.trimEnd()}\n\n${managed}`
      : managed;
  }
  writeFileSync(path, next, "utf-8");
  return { path, written: true };
}

export type NpmRegistryPackageInfo = {
  name: string;
  versions: string[];
  latest?: string;
  path: string;
};

/** List packages from Verdaccio storage (local private packages). */
export function listNpmRegistryPackages(
  dataDir: string,
): NpmRegistryPackageInfo[] {
  const storage = npmRegistryStorageDir(dataDir);
  if (!existsSync(storage)) return [];
  const out: NpmRegistryPackageInfo[] = [];

  const visitPackageDir = (dir: string, name: string): void => {
    const metaPath = join(dir, "package.json");
    // Verdaccio stores as storage/@scope/name/package.json (couchdb doc)
    if (!existsSync(metaPath)) return;
    try {
      const doc = JSON.parse(readFileSync(metaPath, "utf-8")) as {
        name?: string;
        versions?: Record<string, unknown>;
        "dist-tags"?: { latest?: string };
      };
      const versions = Object.keys(doc.versions ?? {}).sort();
      if (!versions.length && !doc.name) return;
      out.push({
        name: doc.name ?? name,
        versions,
        latest: doc["dist-tags"]?.latest ?? versions[versions.length - 1],
        path: dir,
      });
    } catch {
      /* skip */
    }
  };

  for (const entry of readdirSync(storage)) {
    if (entry.startsWith(".")) continue;
    const full = join(storage, entry);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    if (entry.startsWith("@")) {
      for (const pkg of readdirSync(full)) {
        if (pkg.startsWith(".")) continue;
        visitPackageDir(join(full, pkg), `${entry}/${pkg}`);
      }
    } else {
      visitPackageDir(full, entry);
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

/** URL containers use to reach the host-bound registry (Docker Desktop DNS). */
export function npmRegistryDockerUrl(
  meta: Pick<NpmRegistryMeta, "port">,
): string {
  return `http://host.docker.internal:${meta.port}/`;
}

/**
 * Canonical registry env values for managed projects (.env / .env.docker /
 * CI secrets). Phases and the build-process configurator write these into
 * product env files; docker-compose passes the DOCKER_URL as a build ARG.
 *
 * Contract: *_URL values include the protocol (used for registry mappings and
 * `pnpm publish --registry`). *_AUTH_HOST values are host:port WITHOUT
 * protocol — the shape .npmrc nerf-dart auth lines require:
 *   //${SLOPCONTROL_NPM_REGISTRY_AUTH_HOST}/:_authToken=${SLOPCONTROL_NPM_REGISTRY_TOKEN}
 */
export function npmRegistryEnvValues(
  meta: Pick<NpmRegistryMeta, "url" | "port" | "authToken">,
): Record<string, string> {
  let authHost = `127.0.0.1:${meta.port}`;
  try {
    authHost = new URL(meta.url).host || authHost;
  } catch {
    // keep host:port fallback derived from the port
  }
  return {
    SLOPCONTROL_NPM_REGISTRY_URL: meta.url,
    SLOPCONTROL_NPM_REGISTRY_DOCKER_URL: npmRegistryDockerUrl(meta),
    SLOPCONTROL_NPM_REGISTRY_AUTH_HOST: authHost,
    SLOPCONTROL_NPM_REGISTRY_DOCKER_AUTH_HOST: `host.docker.internal:${meta.port}`,
    SLOPCONTROL_NPM_REGISTRY_TOKEN: meta.authToken,
  };
}

export type NpmRegistryPackageFreshness = {
  name: string;
  stale: boolean;
  reason: string;
  tarballMtime?: string;
  distMtime?: string;
};

function upsertEnvLine(body: string, key: string, value: string): string {
  const re = new RegExp(`^${key}=.*$`, "m");
  const line = `${key}=${value}`;
  if (re.test(body)) return body.replace(re, line);
  const trimmed = body.replace(/\s*$/, "");
  return trimmed ? `${trimmed}\n${line}\n` : `${line}\n`;
}

/** True when the project's .gitignore covers the given env file (secret-safe). */
function envFileGitignored(projectRoot: string, rel: string): boolean {
  const path = join(projectRoot, ".gitignore");
  if (!existsSync(path)) return false;
  const body = readFileSync(path, "utf-8");
  const base = rel.replace(/^\//, "");
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line.startsWith("!")) continue;
    const norm = line.replace(/^\//, "").replace(/^\*\*\//, "");
    if (norm === base) return true;
    if (norm.endsWith("*") && base.startsWith(norm.slice(0, -1))) return true;
  }
  return false;
}

export type ProjectRegistryEnvWrite = {
  files: string[];
  tokenWritten: boolean;
};

/**
 * Deterministically upsert the canonical registry env values into a managed
 * project's env files. The LLM never touches these (secrets-bearing) files —
 * this is the ONLY writer, called by the build-process onboarding/configure
 * service.
 *
 * `.env` gets all five values: it is docker-compose's interpolation source
 * for the build ARG contract. `.env.docker` gets the DOCKER_* trio. The
 * TOKEN is only written when the target file is gitignored; otherwise the
 * operator sources it from `GET /projects/:id/build-process` (registryEnv).
 */
export function writeProjectRegistryEnv(opts: {
  projectRoot: string;
  meta: Pick<NpmRegistryMeta, "url" | "port" | "authToken">;
}): ProjectRegistryEnvWrite {
  const values = npmRegistryEnvValues(opts.meta);
  const files: string[] = [];
  let tokenWritten = false;

  const targets: Array<{ rel: string; keys: string[] }> = [
    {
      rel: ".env",
      keys: [
        "SLOPCONTROL_NPM_REGISTRY_URL",
        "SLOPCONTROL_NPM_REGISTRY_DOCKER_URL",
        "SLOPCONTROL_NPM_REGISTRY_AUTH_HOST",
        "SLOPCONTROL_NPM_REGISTRY_DOCKER_AUTH_HOST",
        "SLOPCONTROL_NPM_REGISTRY_TOKEN",
      ],
    },
    {
      rel: ".env.docker",
      keys: [
        "SLOPCONTROL_NPM_REGISTRY_DOCKER_URL",
        "SLOPCONTROL_NPM_REGISTRY_DOCKER_AUTH_HOST",
        "SLOPCONTROL_NPM_REGISTRY_TOKEN",
      ],
    },
  ];

  for (const target of targets) {
    const abs = join(opts.projectRoot, target.rel);
    const prior = existsSync(abs) ? readFileSync(abs, "utf-8") : "";
    const secretSafe = envFileGitignored(opts.projectRoot, target.rel);
    let body = prior;
    if (!body.trim()) {
      body = "# SlopControl npm registry coordinates (managed — do not hand-edit).\n";
    }
    for (const key of target.keys) {
      if (key === "SLOPCONTROL_NPM_REGISTRY_TOKEN" && !secretSafe) continue;
      body = upsertEnvLine(body, key, values[key] ?? "");
    }
    if (body !== prior) {
      writeFileSync(abs, body, "utf-8");
      files.push(target.rel);
    }
    if (target.keys.includes("SLOPCONTROL_NPM_REGISTRY_TOKEN") && secretSafe) {
      tokenWritten = true;
    }
  }
  return { files, tokenWritten };
}
/** Newest file mtime (ms) under a dir, recursive. Null when missing/empty. */
export function dirMaxMtimeMs(dir: string): number | null {
  if (!existsSync(dir)) return null;
  let max = 0;
  const walk = (d: string): void => {
    for (const entry of readdirSync(d)) {
      if (entry.startsWith(".")) continue;
      const full = join(d, entry);
      let st;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      if (st.isDirectory()) {
        walk(full);
      } else if (st.mtimeMs > max) {
        max = st.mtimeMs;
      }
    }
  };
  walk(dir);
  return max > 0 ? max : null;
}

/**
 * Cheap staleness check: is the project's build output newer than the
 * tarball currently sitting in the registry? Catches "edited src, rebuilt
 * dist, never republished" before a consumer's clean install does.
 */
export function npmRegistryPackageFreshness(opts: {
  dataDir: string;
  name: string;
  distDir: string;
}): NpmRegistryPackageFreshness {
  const pkg = listNpmRegistryPackages(opts.dataDir).find(
    (p) => p.name === opts.name,
  );
  if (!pkg) {
    return {
      name: opts.name,
      stale: true,
      reason: "package not found in registry storage (never published?)",
    };
  }
  let tarballMax = 0;
  for (const entry of readdirSync(pkg.path)) {
    if (!entry.endsWith(".tgz")) continue;
    try {
      const mt = statSync(join(pkg.path, entry)).mtimeMs;
      if (mt > tarballMax) tarballMax = mt;
    } catch {
      /* skip */
    }
  }
  if (!tarballMax) {
    return {
      name: opts.name,
      stale: true,
      reason: "no tarball found in registry storage",
    };
  }
  const distMax = dirMaxMtimeMs(opts.distDir);
  if (distMax === null) {
    return {
      name: opts.name,
      stale: true,
      reason: `dist dir missing or empty: ${opts.distDir}`,
      tarballMtime: new Date(tarballMax).toISOString(),
    };
  }
  const stale = distMax > tarballMax;
  return {
    name: opts.name,
    stale,
    reason: stale
      ? "dist output is newer than the published tarball — republish needed"
      : "published tarball is up to date with dist output",
    tarballMtime: new Date(tarballMax).toISOString(),
    distMtime: new Date(distMax).toISOString(),
  };
}

export function jamPackageNameForElement(elementId: string): string {
  const id = elementId
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "") || "element";
  return `@jam/${id}`;
}

/**
 * Scaffold an npm package directory from design-element src files.
 * Always produces a proper @jam/<id> package.json. When src is empty,
 * exports mock.html / tokens.css so the registry shape stays consistent.
 * Returns the package root path (created under elementVersionDir/npm-package).
 */
export function scaffoldElementNpmPackage(opts: {
  outDir: string;
  elementId: string;
  version: number | string;
  label?: string;
  srcFiles: Record<string, string>;
  description?: string;
  mockHtml?: string;
  tokensCss?: string;
}): {
  packageRoot: string;
  packageName: string;
  packageVersion: string;
  packageJsonPath: string;
} {
  const packageName = jamPackageNameForElement(opts.elementId);
  const packageVersion =
    typeof opts.version === "number"
      ? `${opts.version}.0.0`
      : String(opts.version);
  const packageRoot = opts.outDir;
  mkdirSync(packageRoot, { recursive: true });

  const files = { ...opts.srcFiles };
  const hasCode = Object.keys(files).length > 0;
  const mockHtml = opts.mockHtml?.trim() ?? "";
  const tokensCss = opts.tokensCss?.trim() ?? "";

  if (mockHtml) {
    writeFileSync(join(packageRoot, "mock.html"), `${mockHtml}\n`, "utf-8");
  }
  if (tokensCss) {
    writeFileSync(join(packageRoot, "tokens.css"), `${tokensCss}\n`, "utf-8");
  }

  if (!hasCode && !mockHtml) {
    files["index.js"] =
      `/** @jam/${opts.elementId} — placeholder */\nexport {};\n`;
  }

  for (const [rel, body] of Object.entries(files)) {
    const dest = join(packageRoot, rel);
    mkdirSync(join(dest, ".."), { recursive: true });
    writeFileSync(dest, body, "utf-8");
  }

  const entries = Object.keys(files);
  const mainFile = hasCode
    ? entries.find((f) => /^index\.(js|mjs|cjs|ts|tsx)$/i.test(f)) ||
      entries.find((f) => /\.(tsx|ts|js|mjs|cjs)$/i.test(f)) ||
      entries[0]!
    : mockHtml
      ? "mock.html"
      : "index.js";

  const exports: Record<string, unknown> = {};
  if (hasCode || mainFile) {
    exports["."] = {
      default: `./${mainFile}`,
      import: `./${mainFile}`,
    };
  }
  if (mockHtml) {
    exports["./mock.html"] = "./mock.html";
    if (!hasCode) {
      exports["."] = "./mock.html";
    }
  }
  if (tokensCss) {
    exports["./tokens.css"] = "./tokens.css";
  }

  const pkg = {
    name: packageName,
    version: packageVersion,
    description:
      opts.description ||
      opts.label ||
      `SlopControl shared element ${opts.elementId}`,
    type: "module",
    main: mainFile,
    module: mainFile,
    types:
      hasCode && /\.tsx?$/i.test(mainFile) ? mainFile : undefined,
    exports,
    files: ["**/*"],
    keywords: ["slopcontrol", "jam", opts.elementId],
    license: "UNLICENSED",
    private: false,
    publishConfig: {
      access: "public",
    },
  };

  const packageJsonPath = join(packageRoot, "package.json");
  writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf-8");
  return { packageRoot, packageName, packageVersion, packageJsonPath };
}
