import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ProjectConfig } from "@slopcontrol/types";
import { loadDotEnvFile } from "./dotenv.js";

/** Dotenv files merged weak → strong (later wins within the file stack). */
export const PROJECT_ENV_FILE_STACK = [
  ".env.example",
  ".env.docker.example",
  ".env.test.example",
  ".env",
  ".env.local",
  ".env.docker",
  ".env.test",
  ".env.development.local",
  ".env.test.local",
  ".env.production.local",
] as const;

/** Generated file written into worktrees so dotenv-from-cwd apps see resolved env. */
export const WORKTREE_RESOLVED_ENV_FILE = ".env.slopcontrol";

export type ResolvedProjectEnv = {
  env: Record<string, string>;
  /** Keys that came from process.env overrides / passthrough */
  fromProcess: string[];
  /** Files that contributed at least one key */
  fromFiles: string[];
  notes: string[];
};

function applyValueMap(
  env: Record<string, string>,
  map?: Record<string, string>,
): void {
  if (!map) return;
  for (const [key, value] of Object.entries(env)) {
    if (map[value]) {
      env[key] = map[value];
    }
  }
}

/**
 * Technology-agnostic project env resolution.
 *
 * Order: example files → real dotenv files → process.env wins for keys in
 * the merge (and optional passthrough keys/prefixes). Then envMap / llmModelMap.
 */
export function resolveProjectEnv(opts: {
  projectRoot: string;
  config: Pick<
    ProjectConfig,
    | "worktreeSyncPaths"
    | "envMap"
    | "envPassthroughKeys"
    | "envPassthroughPrefixes"
    | "llmModelMap"
    | "llmTestEnvFile"
  >;
  processEnv?: NodeJS.ProcessEnv;
}): ResolvedProjectEnv {
  const processEnv = opts.processEnv ?? process.env;
  const notes: string[] = [];
  const fromFiles: string[] = [];
  const env: Record<string, string> = {};

  const fileStack = [
    ...PROJECT_ENV_FILE_STACK,
    ...(opts.config.worktreeSyncPaths ?? []).filter(
      (p) => !PROJECT_ENV_FILE_STACK.includes(p as (typeof PROJECT_ENV_FILE_STACK)[number]),
    ),
  ];
  // Dedupe preserving order
  const seenFiles = new Set<string>();
  for (const rel of fileStack) {
    if (seenFiles.has(rel)) continue;
    seenFiles.add(rel);
    const path = join(opts.projectRoot, rel);
    const parsed = loadDotEnvFile(path);
    if (Object.keys(parsed).length === 0) continue;
    Object.assign(env, parsed);
    fromFiles.push(rel);
  }

  const fromProcess: string[] = [];
  const fileKeys = new Set(Object.keys(env));
  const passthroughKeys = new Set(opts.config.envPassthroughKeys ?? []);
  const prefixes = opts.config.envPassthroughPrefixes ?? [];

  for (const [key, raw] of Object.entries(processEnv)) {
    if (raw === undefined) continue;
    const value = String(raw);
    const inFiles = fileKeys.has(key);
    const listed = passthroughKeys.has(key);
    const prefixed = prefixes.some((p) => p.length > 0 && key.startsWith(p));
    if (inFiles || listed || prefixed) {
      env[key] = value;
      fromProcess.push(key);
    }
  }

  if (fromProcess.length > 0) {
    notes.push(`process.env overrides/passthrough: ${fromProcess.length} key(s)`);
  }

  // Generic remaps, then llmModelMap as convenience for model IDs
  applyValueMap(env, opts.config.envMap);
  applyValueMap(env, opts.config.llmModelMap);

  notes.push(
    `resolved ${Object.keys(env).length} env key(s) from ${fromFiles.length} file(s)`,
  );

  return { env, fromProcess, fromFiles, notes };
}

/** Serialize env map to dotenv format (no secrets redaction — file is gitignored). */
export function formatDotEnv(env: Record<string, string>): string {
  const lines = [
    "# Generated by SlopControl — do not commit. Mirrors resolved project env for worktree/CI parity.",
    "",
  ];
  for (const key of Object.keys(env).sort()) {
    const value = env[key] ?? "";
    const needsQuotes = /[\s#"']/.test(value);
    lines.push(
      needsQuotes
        ? `${key}="${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
        : `${key}=${value}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * Write resolved env into a worktree (or project root) as `.env.slopcontrol`.
 */
export function writeResolvedEnvToWorktree(opts: {
  worktreePath: string;
  env: Record<string, string>;
}): string {
  const path = join(opts.worktreePath, WORKTREE_RESOLVED_ENV_FILE);
  writeFileSync(path, formatDotEnv(opts.env), "utf-8");
  return WORKTREE_RESOLVED_ENV_FILE;
}

export function mergeEnvRecords(
  ...layers: Array<Record<string, string> | undefined>
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const layer of layers) {
    if (layer) Object.assign(out, layer);
  }
  return out;
}

/** Whether a path exists and looks like a writable data dir parent for mastra.db */
export function probeMastraDbFile(dbPath: string): {
  ok: boolean;
  path: string;
  detail: string;
} {
  try {
    if (existsSync(dbPath)) {
      return { ok: true, path: dbPath, detail: "mastra.db present" };
    }
    // Parent must exist / be creatable — existence of parent dir is enough for "configured"
    const parent = join(dbPath, "..");
    if (existsSync(parent)) {
      return {
        ok: true,
        path: dbPath,
        detail: "mastra.db not created yet (will be on first Memory use)",
      };
    }
    return {
      ok: false,
      path: dbPath,
      detail: "dataDir parent missing — Mastra Memory cannot persist",
    };
  } catch (error) {
    return {
      ok: false,
      path: dbPath,
      detail: error instanceof Error ? error.message : String(error),
    };
  }
}
